plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.9.23'
    id 'maven-publish'
}

group = 'io.github.deficuet'
version = '0.2.0_a1'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7'
    implementation 'org.json:json:20240303'
    implementation 'org.lz4:lz4-java:1.8.0'
    implementation 'org.tukaani:xz:1.10'
    implementation 'org.brotli:dec:0.1.2'
    implementation 'org.apache.commons:commons-compress:1.28.0'
    implementation 'com.github.Deficuet:JImageUtils:0.0.6'
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(17)
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
